#!/bin/bash
# This file should not be modified -- make local changes to /etc/ppp/ip-up.local instead !

# This script is called with the following arguments:
# Arg Name
# $1 Interface name
# $2 The tty
# $3 The link speed
# $4 Local IP number
# $5 Peer IP number
# $6 Optional ``ipparam'' value foo

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

#LOGDEVICE=$6
#REALDEVICE=$1

[ -f /etc/sysconfig/network-scripts/ifcfg-${LOGDEVICE} ] && /etc/sysconfig/network-scripts/ifup-post --realdevi$

/etc/ppp/ip-up.ipv6to4 ${LOGDEVICE}

[ -x /etc/ppp/ip-up.local ] && /etc/ppp/ip-up.local "$@"
# routing automatico quando le stazioni si collegano
# routing automatico quando le stazioni si collegano
case "$5" in
       100.102.0.1)
                ip link set $1 down
                ip link set $1 name pptp_lao0
                ip link set pptp_lao0 up
                sysctl net.ipv4.ip_forward = 1
                sysctl net.ipv4.conf.pptp_lao0.forwarding=1
                ip route add 192.168.21.0/24 via 100.102.0.1 dev pptp_lao0
                
                if iptables -C FORWARD -s 160.97.12.222 -j ACCEPT;\
                then echo 'pptp_lao0 FORWARD rules already present.';\
                else iptables -I FORWARD 3 -s 160.97.12.222 -j ACCEPT;\
                fi
                
                iptables -t nat -I POSTROUTING 1 -s 160.97.12.222 -d 192.168.21.0/24 -o pptp_lao0 -j MASQUERADE
                iptables -t nat -I POSTROUTING 1 -s 160.97.12.222 -d 100.102.0.1 -o pptp_lao0 -j MASQUERADE


                ;;
        *)
esac

exit 0


