#! /bin/bash
#
### BEGIN INIT INFO
# Provides:          ovpn
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $network $time
# Should-Stop:       $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the ovpn client daemon
# Description:       Controls the main ovpn client  daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Start oVPN"
    cd  /opt/ovpn
    openvpn --config client.ovpn --daemon
    ;;
  stop)
    echo "Stop VPN"
    killall -TERM openvpn
    ;;
  *)
    echo "Usage: /etc/init.d/vpn_access {start|stop}"
    exit 1
    ;;
esac

exit 0
